name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  test:
    runs-on: macOS-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test macOS
        run: exec ./.github//scripts/test.sh

